@startuml
'https://plantuml.com/class-diagram

App <|-- PrintList
App <|-- ReadFile


class App {
+main()
+filterNames()
}

class PrintList {
+printOut()
+printEntry()
}

class ReadFile {
+addPeople ()
+readEntry()
}

@enduml